name: medical-llm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain
      - faiss-cpu
      - chromadb
      - openai
      - tiktoken
      - datasets
      - pandas
      - scikit-learn
      - streamlit
      - jupyterlab